# General
set -g set-clipboard on         # Use system clipboard
set -g detach-on-destroy off    # Don't exit from tmux when closing a session
set -g escape-time 0            # Remove delay for exiting insert mode with ESC in Neovim
set -g history-limit 1000000    # Increase history size (from 2,000)
set -g mouse on                 # Enable mouse support
set -g status-interval 3        # Update the status bar every 3 seconds (default: 15 seconds)
set -g allow-passthrough on     # Allow programs in the pane to bypass tmux (e.g. for image preview)
set -g status-position top      # Move status bar to the top of the screen

# Set prefix key
unbind C-b              # Unbind the default prefix key
set -g prefix C-a   # Set new prefix key to Ctrl+A

# Refresh tmux config with r
unbind r
bind r source-file ~/.psmux.conf \; display-message "tmux config reloaded"

# Don't exit copy mode when dragging with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on # Automatically renumber windows when one is closed
