git:
  paging:
    colorArg: always
    pager: delta --paging=never --features=side-by-side

gui:
  showIcons: true
  mouseEvents: true
  sidePanelWidth: 0.3
  expandFocusedSidePanel: true
  border: rounded
